### PR TITLE
Create 2021-01-15-Stickers!.md

### PR DESCRIPTION
**Pull request by drewhutcheon**
posting sticker announement

### CODE REVIEW

**Review by devinsmiley — APPROVED** [review]
New blog post. I'll be interested to see if having the '!' in the markdown file name affects anything.

**Comment by SemperRuminare** [comment]
Need to rename or double check on '!' before merging - I'm curious is we should do a staging/test repo or if there's a better way than local tests

Also I want to put a picture in here before merging too

**Comment by drewhutcheon** [comment]
@devinsmiley do you have that sticker pic you used on Instagram?

**Comment by devinsmiley** [comment]
image

**Comment by devinsmiley** [comment]
image

@drewhutcheon

**Comment by SemperRuminare** [comment]
image

Looks like '!' is okay. Add the picture, then we can merge

**Review by devinsmiley — APPROVED** [review]
'!' in file name tested with no negative effect. Looks good! Ready to merge.

**Review by devinsmiley — APPROVED** [review]
Close up photo included in the post.

**Pull request merged**
