### PR TITLE
Banner Injector Implementation and Security Updates

### PR DESCRIPTION
**Pull request by elisoncrum**
## Summary
1. Introduces Github Actions that builds Jekyll, injects banner, pushes to branch `gh-pages` and then deploys static content.
2. Update dependencies based on Snyk and Dependabot

## Testing
Tested in forked repository pushing to Github Pages.

## Possible Repo Breaking
- Since this changes the environment where Github Pages pushes from, traditionally the `pages-build-deployment` action handles pushing to Github Pages utilizing the same branch as main. This code will automatically deploy without generating a separate branch. Possibly issues of environment.
- Base URL configuration. In order for certain assets to work while injecting the banner, it generates HTML using Jinja2. Required to specify URL.
  - Reference `_config.yml` and `banner-config.yml`

## Reference
**Demo Page**
https://elisoncrum.github.io/marinecoders.github.io

**Custom Banner Injection**
https://github.com/elisoncrum/banner-injector

### CODE REVIEW

**Comment by elisoncrum** [comment]
Making modifications from recommendations from @GregPetropoulos. Removing in line styling and modifying mobile breakpoints.

**Comment by SemperRuminare** [comment]
The only thing I'm not comfortable with is pulling latest on banner injector, would like it to be specifically a tagged release pull at a minimum, best would be co-located in Marine Coders repo

**Review by SemperRuminare — APPROVED** [review]
Looks great

**Comment by SemperRuminare** [comment]
shut up ossar, let's try it

**Pull request merged**
