### PR TITLE
Create 2021-02-09-II-MIG-Cell-Established.md

### PR DESCRIPTION
**Pull request by drewhutcheon**
II MIG Cell Post

### CODE REVIEW

**Review by devinsmiley — DISMISSED** [review]
II MIG Cell blog post added. Looks good. Add a comment about the 'Codesmiths' once the nickname is approved?

**Comment by SemperRuminare** [comment]
90% sure this will fail due to lack of '-' in md file name. Will test tomorrow.

**Comment by SemperRuminare** [comment]
> 90% sure this will fail due to lack of '-' in md file name. Will test tomorrow.

Man should really add some checks in the posts for github actions - who's even running this place

**Comment by drewhutcheon** [comment]
Fixed

**Comment by SemperRuminare** [comment]
image

Needs title fixing

**Review by devinsmiley — APPROVED** [review]
Looks like the title issues have been fixed.

**Pull request merged**
